name: streaming_lakehouse
version: 0.1.0
config-version: 2

profile: streaming_lakehouse

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
test-paths: ["tests"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  streaming_lakehouse:
    bronze:
      +materialized: view
      +schema: bronze
    silver:
      +materialized: view
      +schema: silver
    gold:
      +materialized: table
      +schema: gold

seeds:
  streaming_lakehouse:
    +schema: bronze
    raw_events:
      +column_types:
        event_id: varchar
        event_type: varchar
        actor_login: varchar
        repo_name: varchar
        event_created_at: timestamp
        ingested_at: timestamp
        payload: varchar

vars:
  raw_events_source: "{{ env_var('BQ_DATASET_BRONZE', 'bronze') }}.raw_events"
