name: streaming_lakehouse
version: 0.1.0
config-version: 2

profile: streaming_lakehouse

model-paths: ["models"]
test-paths: ["tests"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  streaming_lakehouse:
    bronze:
      +materialized: view
      +schema: bronze
    silver:
      +materialized: view
      +schema: silver
    gold:
      +materialized: table
      +schema: gold

vars:
  raw_events_source: "{{ env_var('BQ_DATASET_BRONZE', 'bronze') }}.raw_events"
